name: "Publish tags to FlakeHub"
on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      tag:
        description: "The existing tag to alias as latest"
        type: "string"
        required: true
jobs:
  tag-latest:
    - name: Run latest-tag
      uses: EndBug/latest-tag@latest
